#
# @description : My config file for alacritty
# @author : Eric Wartelle
# @version : 1.0
#

working_directory = "/home/tontonleric/Projects"

# Importing the catpuccin color scheme
import = [
	# "~/.config/alacritty/catppuccin-mocha.toml"
	# "~/.config/alacritty/catppuccin-latte.toml"
	"~/.config/alacritty/catppuccin-frappe.toml"
	# "~/.config/alacritty/catppuccin-macchiato.toml"
]

# On va spécifier le répertoire de départ

# On va spécifier le shell utilisé
[shell]
program = "/usr/bin/tmux"
args = []

# Environment variables
[env]
TERM = "xterm-256color"

[window]
title = "El Rico està loco"
opacity = 0.95

# Font
[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"


